name: example
description: example
version: 0.1.1
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sms: ^0.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: