name: flutter_otp
description: A Flutter package for sending OTP and validation of OTP. Four digit OTP (customizable) is sent as a SMS to the given phone number. Also option is provided to verify the OTP entered by the user. SMS can be sent to any country to the specified country code.
version: 0.1.0
authors:
  - Fawaz Hussain <fawazfound@gmail.com>
  - Jerin Francis <jerinfrancis77@gmail.com>
homepage: https://github.com/JerinFrancisA/flutter_otp

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sms: ^0.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: